language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - GH_REF=github.com/rustyb/phr.ie.git
  - DEPLOY_BRANCH=design-system
  - secure: E2tIjpKEo+UPIlEJTVoIHAmwj9y5jbaGkDVyVT5Zq7+ldodmX7BxNvJ9nltLarIL44/wq65wZn2RgnQa5ujneAPiIOSM8pzqJervrIJQYvkKKfRezayvwKnFEFteTYUjWae73M5hFx2h6rsBa2wAJSL+IxCvC3UCr/RID7vs8wb7HZv6ZETwKxzg1bH+HciByqqLtBgwgM7+tKkn3e4+0+9VLndNo47dgF9ogahDHx9SV2iEa1gr6p7CLPm3yGXzvYD3jbDv2FO2P0Khq4YF8li3TqLANZgYHbuS5Z68di2VNDzToeo2uk6UMvWRUAj4giMPzVxIyqTVLts2qhm2b92yfb5vJclxaBubvlyB//QmnRAGaYGfqN1UhfcVnqvbCXMOFgdZKFVr3m7OrOk3Ud/MugTpRmEOM2QhxZRyz8Hvjrbcttl4C5GtxHeoU+8+an9urDeKqIf7g5KgnCiBVsQwpX4gwThmYhRCKDIlm8jZ+WrnnrYU5fqAFSdo3qK6ejBNTeXIB6Z2m/cP0bAaz62jqKPw0AE/6qKeNq4jGXPGAXiSBClPPsJ5PjqLBPxp/nRqUCV3shh7wlWtHyB1Rzrnh7VkEASjbIIPcQQrXQKa26KZCHHqQI4rpe0HVCFsIE2QhnVmz8xlpKd/T85UCwza+4EhP+wNqlIGUqSonLs=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
before_script:
- gem install jekyll
script:
- npm run build
# after_success:
# - "./.build_scripts/deploy.sh"

deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
