# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Panacea Research
email: info@phr.ie
description: > # this means to ignore newlines until "baseurl:"
  Panacea Research providing market intelligence to a variety of sectors including energy development and public health infrastructure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.phr.ie/" # the base hostname & protocol for your site
twitter_username: rusty1052
github_username:  rustyb

# Build settings
# markdown: kramdown

permalink: pretty

source: app
future: true

exclude: 
  - node_modules
  - jekyll
  - etc
  - bower_components
  - src
  - gulpfile.js
  - bower.json 
  - package.json
  - .jekyll-cache
  - .ruby-version
  - set_up_db_for_census.md

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author: "PHR Team"

plugins:
  - jekyll-include-cache
  - jekyll-commonmark

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]