# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Panacea Health Research
email: info@phr.ie
description: > # this means to ignore newlines until "baseurl:"
  Panacea Health Research LTD. is an Irish startup specialising in spatial
  health research for the elderly care sector.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.phr.ie/" # the base hostname & protocol for your site
twitter_username: rusty1052
github_username:  rustyb

# Build settings
markdown: kramdown

permalink: pretty

exclude: [node_modules, jekyll, etc, bower_components, src, gulpfile.js, bower.json, package.json]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      tyoe: "posts"
    values:
      author: "PHRs Team"
